# Generated by Django 4.0.5 on 2022-06-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genz',
            name='sentence_non_entities',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
